# Generated by Django 3.0.8 on 2020-08-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200801_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
