# Generated by Django 3.0.8 on 2020-08-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_axisStaff',
            field=models.BooleanField(default=False),
        ),
    ]
