# Generated by Django 3.0.8 on 2020-07-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0002_auto_20200730_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
