# Generated by Django 3.0.8 on 2020-08-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0006_auto_20200801_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
