# Generated by Django 3.0.8 on 2020-08-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0007_auto_20200801_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='device',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
