# Generated by Django 3.0.8 on 2020-08-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0009_auto_20200804_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='province',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
