# Generated by Django 3.0.8 on 2020-08-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0012_auto_20200804_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='device',
        ),
    ]
