# Generated by Django 3.0.8 on 2020-08-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0013_remove_customer_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
