# Generated by Django 3.0.8 on 2020-08-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0014_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
