# Generated by Django 3.0.8 on 2020-08-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0015_remove_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
