# Generated by Django 3.0.8 on 2020-08-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0016_category_date_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
