# Generated by Django 3.0.8 on 2020-08-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0019_remove_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='suburb',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
