# Generated by Django 3.0.8 on 2020-09-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0020_shippingaddress_suburb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.TextField(default=211, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description3',
            field=models.TextField(default=211, max_length=2000),
            preserve_default=False,
        ),
    ]
