# Generated by Django 3.1.5 on 2021-01-09 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0022_auto_20210109_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shippingDetails',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='shippingDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.shippingaddress'),
        ),
    ]
