# Generated by Django 3.1.5 on 2021-01-09 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0024_shippingaddress_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='shippingDetails',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.customer'),
        ),
    ]
