# Generated by Django 3.1.5 on 2021-01-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0027_remove_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
    ]
