# Generated by Django 3.1.5 on 2021-01-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0028_remove_shippingaddress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=60, null=True, unique=True, verbose_name='email'),
        ),
    ]
