# Generated by Django 3.1.5 on 2021-01-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0031_auto_20210109_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description3',
        ),
    ]
