# Generated by Django 3.1.5 on 2021-01-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0033_auto_20210112_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'sub category', 'verbose_name_plural': 'sub categories'},
        ),
    ]
