# Generated by Django 3.1.5 on 2021-01-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0034_auto_20210112_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
