# Generated by Django 3.1.5 on 2021-01-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0036_auto_20210112_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLayer2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('has_subcategory', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.category')),
            ],
            options={
                'verbose_name': 'Category Layer 2',
                'verbose_name_plural': 'Category Layer 2',
            },
        ),
        migrations.CreateModel(
            name='CategoryLayer3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('has_subcategory', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.categorylayer2')),
            ],
            options={
                'verbose_name': 'Category Layer 3',
                'verbose_name_plural': 'Category Layer 3',
            },
        ),
        migrations.CreateModel(
            name='CategoryLayer4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('has_subcategory', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.categorylayer3')),
            ],
            options={
                'verbose_name': 'Category Layer 4',
                'verbose_name_plural': 'Category Layer 4',
            },
        ),
        migrations.CreateModel(
            name='CategoryLayer5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('has_subcategory', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.categorylayer4')),
            ],
            options={
                'verbose_name': 'Category Layer 5',
                'verbose_name_plural': 'Category Layer 5',
            },
        ),
        migrations.CreateModel(
            name='CategoryLayer6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('has_subcategory', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.categorylayer5')),
            ],
            options={
                'verbose_name': 'Category Layer 6',
                'verbose_name_plural': 'Category Layer 6',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.categorylayer2'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.categorylayer3'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.categorylayer4'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.categorylayer5'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.categorylayer6'),
        ),
    ]
