# Generated by Django 3.1.5 on 2021-01-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0040_auto_20210115_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='items',
            new_name='count',
        ),
    ]
