# Generated by Django 3.1.5 on 2021-01-26 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0042_auto_20210126_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorylayer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.categorylayer2'),
        ),
        migrations.AddField(
            model_name='product',
            name='categorylayer3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.categorylayer3'),
        ),
        migrations.AddField(
            model_name='product',
            name='categorylayer4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.categorylayer4'),
        ),
        migrations.AddField(
            model_name='product',
            name='categorylayer5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.categorylayer5'),
        ),
        migrations.AddField(
            model_name='product',
            name='categorylayer6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Axis.categorylayer6'),
        ),
    ]
