# Generated by Django 3.0.8 on 2020-08-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collective', '0003_auto_20200801_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectivecustomer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='collectivecustomer',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='collectivecustomer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='collectivecustomer',
            name='profile_pic',
        ),
    ]
