# Generated by Django 3.0.8 on 2020-08-01 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collective', '0004_auto_20200801_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiveColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'collective color',
                'verbose_name_plural': 'collective colors',
            },
        ),
        migrations.CreateModel(
            name='CollectiveSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'collective size',
                'verbose_name_plural': 'collective sizes',
            },
        ),
        migrations.AlterModelOptions(
            name='collectivecategory',
            options={'verbose_name': 'collective category', 'verbose_name_plural': 'collective categories'},
        ),
        migrations.AddField(
            model_name='collectiveproduct',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Collective.CollectiveColor'),
        ),
        migrations.AddField(
            model_name='collectiveproduct',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Collective.CollectiveSize'),
        ),
    ]
