# Generated by Django 3.0.8 on 2020-08-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collective', '0005_auto_20200801_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectivecustomer',
            name='email',
        ),
    ]
