# Generated by Django 3.0.8 on 2020-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collective', '0006_remove_collectivecustomer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectivecustomer',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
