# Generated by Django 3.0.8 on 2020-08-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collective', '0009_auto_20200807_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectiveorder',
            name='complete',
        ),
        migrations.AddField(
            model_name='collectiveorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Payment Confirmed, Processing Order', 'Payment Confirmed, Processing Order'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
