# Generated by Django 3.0.8 on 2020-08-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collective', '0010_auto_20200807_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiveproduct',
            name='image1',
            field=models.ImageField(blank=True, upload_to='collective_product/'),
        ),
        migrations.AlterField(
            model_name='collectiveproduct',
            name='image2',
            field=models.ImageField(blank=True, upload_to='collective_product/'),
        ),
        migrations.AlterField(
            model_name='collectiveproduct',
            name='image3',
            field=models.ImageField(blank=True, upload_to='collective_product/'),
        ),
        migrations.AlterField(
            model_name='collectiveproduct',
            name='image4',
            field=models.ImageField(blank=True, upload_to='collective_product/'),
        ),
    ]
