# Generated by Django 3.0.8 on 2020-07-31 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Africa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Africa.Dish'),
        ),
    ]
