# Generated by Django 3.0.8 on 2020-07-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Africa', '0002_ingredient_dish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
