# Generated by Django 3.0.8 on 2020-07-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Africa', '0003_auto_20200731_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image01',
            field=models.ImageField(default=1, upload_to='main_product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='image02',
            field=models.ImageField(default=1, upload_to='main_product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='image03',
            field=models.ImageField(default=1, upload_to='main_product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='image04',
            field=models.ImageField(default=1, upload_to='main_product/'),
            preserve_default=False,
        ),
    ]
